site_name: Mini Accumulo Cluster

site_description: Mini Accumulo Cluster Documentation
site_author: Logan Asher Jones
site_url: https://loganasherjones.github.io/mini-accumulo-cluster

repo_name: mini-accumulo-cluster
repo_url: https://github.com/loganasherjones/mini-accumulo-cluster
edit_uri: edit/main/docs/

copyright: 'Copyright &copy; 2025 Logan Asher Jones'

theme:
  name: 'material'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: custom-light
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: custom-dark
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.indexes
    - navigation.instant

# Custom colors.
extra_css:
  - stylesheets/extra.css

plugins:
  - search
  # Required to get version numbers working correctly.
  - markdownextradata


markdown_extensions:
  # Core requirement for other things.
  - attr_list

  # Icons
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # Syntax Highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # Content Tabs
  - pymdownx.tabbed:
      alternate_style: true

extra:
  version:
    provider: mike